name: GridHub
version: 0.3.2
description: Multi-repository grid view
dependencies:
  browser: any
  crypto: ">=0.9.0 <0.10.0"
  flux:
    path: './libraries/flux/'
  react: ">=0.5.0 <0.6.0"
  web_skin_react:
    git:
      url: git@github.com:Workiva/web-skin-react.git
      ref: 2.0.2
dev_dependencies:
#  unittest: any
